# -*- coding: utf-8 -*-
"""TH_DeepLearning_Buoi04_Bai03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fVExZEBx0nmZ8IWXc2mg2oi2SAA7LyN

### 1. Khai báo thư viện và tải dữ liệu Fashion-MNIST
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

# Tải tập dữ liệu Fashion-MNIST
(train_images, train_labels), (test_images, test_labels) = datasets.fashion_mnist.load_data()

# Chuẩn hóa dữ liệu pixel về khoảng [0, 1]
train_images, test_images = train_images / 255.0, test_images / 255.0

# Thêm một chiều (channel) cho ảnh để phù hợp với input của CNN (28, 28, 1)
train_images = train_images.reshape((train_images.shape[0], 28, 28, 1))
test_images = test_images.reshape((test_images.shape[0], 28, 28, 1))

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

print(f"Kích thước tập huấn luyện: {train_images.shape}")

"""### 2. Xây dựng cấu trúc mạng CNN"""

model = models.Sequential([
    # Lớp Convolutional đầu tiên
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),

    # Lớp Convolutional thứ hai
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Chuyển đổi thành vector phẳng và đưa vào các lớp Dense
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10) # 10 lớp đầu ra tương ứng với 10 loại quần áo
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()

"""### 3. Huấn luyện mô hình"""

history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))

"""### 4. Đánh giá độ chính xác"""

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)
print(f'\nĐộ chính xác trên tập kiểm tra: {test_acc*100:.2f}%')

# Tạo figure với 2 biểu đồ con
plt.figure(figsize=(12, 4))

# Biểu đồ Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label = 'Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training and Validation Accuracy')
plt.legend(loc='lower right')

# Biểu đồ Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label = 'Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend(loc='upper right')

plt.tight_layout()
plt.show()

"""### 5. Dự đoán và kiểm tra kết quả trên một số ảnh mẫu"""

import numpy as np

# Lấy dự đoán từ mô hình cho tập kiểm tra
predictions = model.predict(test_images)

def plot_image(i, predictions_array, true_label, img):
    true_label, img = true_label[i], img[i]
    plt.grid(False)
    plt.xticks([])
    plt.yticks([])

    plt.imshow(img.reshape(28,28), cmap=plt.cm.binary)

    predicted_label = np.argmax(predictions_array)
    if predicted_label == true_label:
        color = 'blue'
    else:
        color = 'red'

    plt.xlabel(f"{class_names[predicted_label]} {100*np.max(predictions_array):2.0f}% ({class_names[true_label]})", color=color)

# Hiển thị 15 ảnh tiếp theo cùng dự đoán
num_rows = 5
num_cols = 3
num_images = num_rows * num_cols
plt.figure(figsize=(2*2*num_cols, 2*num_rows))
for i in range(num_images):
    plt.subplot(num_rows, 2*num_cols, 2*i+1)
    plot_image(i, predictions[i], test_labels, test_images)

plt.tight_layout()
plt.show()