# -*- coding: utf-8 -*-
"""TH_DeepLearning_Buoi04_Bai02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWseB0LFGj51lIellaTpYUJJWJxj1P2h
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models

# 1. Tải dữ liệu từ tfds
(train_ds, validation_ds), info = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True,
)

# 2. Tiền xử lý dữ liệu
IMG_SIZE = 150

def format_example(image, label):
    image = tf.cast(image, tf.float32)
    image = (image / 127.5) - 1 # Normalize về khoảng [-1, 1]
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    return image, label

train = train_ds.map(format_example).shuffle(1000).batch(32).prefetch(tf.data.AUTOTUNE)
validation = validation_ds.map(format_example).batch(32).prefetch(tf.data.AUTOTUNE)

# 3. Xây dựng mô hình CNN
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),
    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dense(1, activation='sigmoid') # Binary classification
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

# 4. Huấn luyện mô hình
history = model.fit(
    train,
    epochs=10,
    validation_data=validation
)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(len(acc))

plt.figure(figsize=(12, 5))

# Biểu đồ Accuracy
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

# Biểu đồ Loss
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')

plt.show()

import numpy as np
from google.colab import files
from tensorflow.keras.preprocessing import image

# Lấy một vài mẫu từ tập validation để test nhanh
for img_batch, label_batch in validation.take(1):
    prediction = model.predict(img_batch)

    plt.figure(figsize=(10, 10))
    for i in range(3):
        ax = plt.subplot(1, 3, i + 1)
        plt.imshow((img_batch[i] + 1) / 2) # Re-scale để hiển thị
        actual = "Cat" if label_batch[i] == 0 else "Dog"
        pred_label = "Cat" if prediction[i] < 0.5 else "Dog"
        prob = prediction[i][0] if prediction[i] >= 0.5 else 1 - prediction[i][0]

        plt.title(f"Actual: {actual}\nPred: {pred_label} ({prob:.2%})")
        plt.axis("off")
    break

from google.colab import files
from tensorflow.keras.preprocessing import image

uploaded = files.upload()

for fn in uploaded.keys():
  # Dự đoán hình ảnh
  path = '/content/' + fn
  img = image.load_img(path, target_size=(150, 150))
  x = image.img_to_array(img)
  x = (x / 127.5) - 1 # Normalize giống lúc train
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = model.predict(images, batch_size=10)

  plt.imshow(img)
  plt.axis('off')
  if classes[0] > 0.5:
    plt.title(f"{fn} là một chú CHÓ")
  else:
    plt.title(f"{fn} là một chú MÈO")
  plt.show()